name: node-build-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout/@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: |
          npm run dist
      - name: Npm Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Get Name
        id: get_name
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: name
      - name: Get Version
        id: get_version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
      - name: Get Id
        id: get_id
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./src/manifest.json
      - name: Create Zip File
        uses: vimtor/action-zip@v1
        with:
          files: ./publish/${{ steps.get_id.outputs.value }}.jpl
          dest: ./${{ steps.get_name.outputs.value }}_v${{ steps.get_version.outputs.value }}.zip
      - name: Create ChangeLog Text
        id: changelog_text
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/scripts/tag-changelog-config.js
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get_version.outputs.value }}
          prerelease: false
          draft: false
          artifacts: ./${{ steps.get_name.outputs.value }}_v${{ steps.get_version.outputs.value }}.zip
          body: ${{ steps.changelog_text.outputs.changes }}
