name: node-build-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache npm store
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Npm publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Get plugin info
        id: info
        run: |
          package_file=./package.json
          manifest_file=./src/manifest.json
          plugin_name=$(cat $package_file | jq -r '.name')
          plugin_version=$(cat $manifest_file | jq -r '.version')
          plugin_id=$(cat $manifest_file | jq -r '.id')
          echo "name=${plugin_name}" >> $GITHUB_OUTPUT
          echo "version=${plugin_version}" >> $GITHUB_OUTPUT
          echo "id=${plugin_id}" >> $GITHUB_OUTPUT
      - name: Create zip file
        uses: vimtor/action-zip@v1.2
        with:
          files: ./publish/${{ steps.info.outputs.id }}.jpl
          dest: ./${{ steps.info.outputs.name }}_v${{ steps.info.outputs.version }}.zip
      - name: Create changeLog text
        id: changelog_text
        uses: dragonish/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/scripts/tag-changelog-config.cjs
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.info.outputs.version }}
          prerelease: false
          draft: false
          artifacts: ./${{ steps.info.outputs.name }}_v${{ steps.info.outputs.version }}.zip
          body: ${{ steps.changelog_text.outputs.changes }}
