name: node-build-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: |
          npm run dist
      - name: Npm publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Get name
        id: get_name
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: name
      - name: Get version
        id: get_version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
      - name: Get id
        id: get_id
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./src/manifest.json
          property: id
      - name: Create zip file
        uses: vimtor/action-zip@v1.2
        with:
          files: ./publish/${{ steps.get_id.outputs.value }}.jpl
          dest: ./${{ steps.get_name.outputs.value }}_v${{ steps.get_version.outputs.value }}.zip
      - name: Create changeLog text
        id: changelog_text
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/scripts/tag-changelog-config.cjs
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          name: Release ${{ steps.get_version.outputs.value }}
          prerelease: false
          draft: false
          artifacts: ./${{ steps.get_name.outputs.value }}_v${{ steps.get_version.outputs.value }}.zip
          body: ${{ steps.changelog_text.outputs.changes }}
